install:
  ps: Write-Host (Get-Location).Path
  ps: cd c:\projects
  ps: Write-Host (Get-Location).Path
  ps: git clone https://github.com/Microsoft/vcpkg.git

branches:
  only:
    master

configuration:
  Debug

platform:
  x64



test_script:
  - ps: Write-Host "Print from AppVeyor"